var annotated_dup =
[
    [ "CryptoConfig", null, [
      [ "MissingKeyException", "class_crypto_config_1_1_missing_key_exception.html", null ]
    ] ],
    [ "DataTypeConverter", null, [
      [ "InvalidHexException", "class_data_type_converter_1_1_invalid_hex_exception.html", null ]
    ] ],
    [ "iota", null, [
      [ "NodeInfo", "structiota_1_1_node_info.html", null ]
    ] ],
    [ "model", "namespacemodel.html", [
      [ "gradido", null, [
        [ "AddressAlreadyExistException", "classmodel_1_1gradido_1_1_address_already_exist_exception.html", null ],
        [ "DeferredTransfer", "classmodel_1_1gradido_1_1_deferred_transfer.html", null ],
        [ "GradidoBlock", "classmodel_1_1gradido_1_1_gradido_block.html", "classmodel_1_1gradido_1_1_gradido_block" ],
        [ "GradidoTransaction", "classmodel_1_1gradido_1_1_gradido_transaction.html", "classmodel_1_1gradido_1_1_gradido_transaction" ],
        [ "GroupFriendsUpdate", "classmodel_1_1gradido_1_1_group_friends_update.html", "classmodel_1_1gradido_1_1_group_friends_update" ],
        [ "InsufficientBalanceException", "classmodel_1_1gradido_1_1_insufficient_balance_exception.html", null ],
        [ "InvalidCreationException", "classmodel_1_1gradido_1_1_invalid_creation_exception.html", null ],
        [ "PairingTransactionNotMatchException", "classmodel_1_1gradido_1_1_pairing_transaction_not_match_exception.html", null ],
        [ "RegisterAddress", "classmodel_1_1gradido_1_1_register_address.html", "classmodel_1_1gradido_1_1_register_address" ],
        [ "TransactionBase", "classmodel_1_1gradido_1_1_transaction_base.html", "classmodel_1_1gradido_1_1_transaction_base" ],
        [ "TransactionBody", "classmodel_1_1gradido_1_1_transaction_body.html", null ],
        [ "TransactionCreation", "classmodel_1_1gradido_1_1_transaction_creation.html", "classmodel_1_1gradido_1_1_transaction_creation" ],
        [ "TransactionTransfer", "classmodel_1_1gradido_1_1_transaction_transfer.html", "classmodel_1_1gradido_1_1_transaction_transfer" ],
        [ "TransactionValidationException", "classmodel_1_1gradido_1_1_transaction_validation_exception.html", null ],
        [ "TransactionValidationForbiddenSignException", "classmodel_1_1gradido_1_1_transaction_validation_forbidden_sign_exception.html", null ],
        [ "TransactionValidationInvalidInputException", "classmodel_1_1gradido_1_1_transaction_validation_invalid_input_exception.html", "classmodel_1_1gradido_1_1_transaction_validation_invalid_input_exception" ],
        [ "TransactionValidationInvalidSignatureException", "classmodel_1_1gradido_1_1_transaction_validation_invalid_signature_exception.html", null ],
        [ "TransactionValidationMissingSignException", "classmodel_1_1gradido_1_1_transaction_validation_missing_sign_exception.html", null ],
        [ "TransactionValidationRequiredSignMissingException", "classmodel_1_1gradido_1_1_transaction_validation_required_sign_missing_exception.html", null ],
        [ "WrongAddressTypeException", "classmodel_1_1gradido_1_1_wrong_address_type_exception.html", null ]
      ] ],
      [ "IGradidoBlockchain", "classmodel_1_1_i_gradido_blockchain.html", "classmodel_1_1_i_gradido_blockchain" ],
      [ "TransactionEntry", "classmodel_1_1_transaction_entry.html", "classmodel_1_1_transaction_entry" ],
      [ "TransactionsCountException", "classmodel_1_1_transactions_count_exception.html", null ],
      [ "TransactionsManager", "classmodel_1_1_transactions_manager.html", "classmodel_1_1_transactions_manager" ],
      [ "TransactionsManagerBlockchain", "classmodel_1_1_transactions_manager_blockchain.html", "classmodel_1_1_transactions_manager_blockchain" ]
    ] ],
    [ "SealedBoxes", null, [
      [ "DecryptException", "class_sealed_boxes_1_1_decrypt_exception.html", null ]
    ] ],
    [ "AuthenticatedEncryption", "class_authenticated_encryption.html", "class_authenticated_encryption" ],
    [ "BlockchainOrderException", "class_blockchain_order_exception.html", null ],
    [ "CachedDecimal", "class_cached_decimal.html", null ],
    [ "CrossGroupTransactionBuilder", "class_cross_group_transaction_builder.html", null ],
    [ "DecayDecimal", "class_decay_decimal.html", "class_decay_decimal" ],
    [ "Decimal", "class_decimal.html", "class_decimal" ],
    [ "DecryptionFailedException", "class_decryption_failed_exception.html", null ],
    [ "DRHashList", "class_d_r_hash_list.html", null ],
    [ "DRHashListItem", "class_d_r_hash_list_item.html", null ],
    [ "DRMemoryList", "class_d_r_memory_list.html", null ],
    [ "DRStaticHashList", "class_d_r_static_hash_list.html", null ],
    [ "Ed25519SignException", "class_ed25519_sign_exception.html", null ],
    [ "GradidoBlockchainException", "class_gradido_blockchain_exception.html", null ],
    [ "GradidoBlockchainTransactionAlreadyExistException", "class_gradido_blockchain_transaction_already_exist_exception.html", null ],
    [ "GradidoBlockchainTransactionNotFoundException", "class_gradido_blockchain_transaction_not_found_exception.html", null ],
    [ "GradidoInvalidBase64Exception", "class_gradido_invalid_base64_exception.html", null ],
    [ "GradidoInvalidEnumException", "class_gradido_invalid_enum_exception.html", null ],
    [ "GradidoUnknownEnumException", "class_gradido_unknown_enum_exception.html", null ],
    [ "GraphQLRequest", "class_graph_q_l_request.html", null ],
    [ "HandleRequestException", "class_handle_request_exception.html", null ],
    [ "HttpRequest", "class_http_request.html", null ],
    [ "InvalidCrossGroupTransaction", "class_invalid_cross_group_transaction.html", null ],
    [ "InvalidTransactionTypeOnBlockchain", "class_invalid_transaction_type_on_blockchain.html", null ],
    [ "IotaPostRequestException", "class_iota_post_request_exception.html", null ],
    [ "IotaRequest", "class_iota_request.html", "class_iota_request" ],
    [ "IotaRequestException", "class_iota_request_exception.html", null ],
    [ "JsonCakePHPRequest", "class_json_cake_p_h_p_request.html", null ],
    [ "JsonRequest", "class_json_request.html", "class_json_request" ],
    [ "JsonRequestHandler", "class_json_request_handler.html", null ],
    [ "JsonRequestHandlerJwt", "class_json_request_handler_jwt.html", null ],
    [ "JsonRPCException", "class_json_r_p_c_exception.html", null ],
    [ "JsonRPCRequest", "class_json_r_p_c_request.html", null ],
    [ "JwtTokenException", "class_jwt_token_exception.html", null ],
    [ "KeyPairEd25519", "class_key_pair_ed25519.html", "class_key_pair_ed25519" ],
    [ "MathMemory", "class_math_memory.html", null ],
    [ "MemoryBin", "class_memory_bin.html", "class_memory_bin" ],
    [ "MemoryManager", "class_memory_manager.html", null ],
    [ "MemoryManagerException", "class_memory_manager_exception.html", null ],
    [ "MemoryPageStack", "class_memory_page_stack.html", null ],
    [ "Mnemonic", "class_mnemonic.html", "class_mnemonic" ],
    [ "MnemonicException", "class_mnemonic_exception.html", null ],
    [ "MultithreadContainer", "class_multithread_container.html", null ],
    [ "MultithreadContainerLockTimeoutException", "class_multithread_container_lock_timeout_exception.html", null ],
    [ "MultithreadQueue", "class_multithread_queue.html", "class_multithread_queue" ],
    [ "ParseDecimalStringException", "class_parse_decimal_string_exception.html", null ],
    [ "ParseStringToMpfrException", "class_parse_string_to_mpfr_exception.html", null ],
    [ "Passphrase", "class_passphrase.html", "class_passphrase" ],
    [ "PassphraseEmptyWordSourceException", "class_passphrase_empty_word_source_exception.html", null ],
    [ "PocoNetException", "class_poco_net_exception.html", null ],
    [ "Profiler", "class_profiler.html", null ],
    [ "ProtobufArenaMemory", "class_protobuf_arena_memory.html", null ],
    [ "ProtobufJsonSerializationException", "class_protobuf_json_serialization_exception.html", null ],
    [ "ProtobufParseException", "class_protobuf_parse_exception.html", null ],
    [ "ProtobufSerializationException", "class_protobuf_serialization_exception.html", null ],
    [ "RapidjsonInvalidMemberException", "class_rapidjson_invalid_member_exception.html", null ],
    [ "RapidjsonMissingMemberException", "class_rapidjson_missing_member_exception.html", null ],
    [ "RapidjsonParseErrorException", "class_rapidjson_parse_error_exception.html", null ],
    [ "RequestEmptyResponseException", "class_request_empty_response_exception.html", null ],
    [ "RequestException", "class_request_exception.html", null ],
    [ "RequestResponseCakePHPException", "class_request_response_cake_p_h_p_exception.html", null ],
    [ "RequestResponseErrorException", "class_request_response_error_exception.html", null ],
    [ "RequestResponseInvalidJsonException", "class_request_response_invalid_json_exception.html", "class_request_response_invalid_json_exception" ],
    [ "SecretKeyCryptography", "class_secret_key_cryptography.html", "class_secret_key_cryptography" ],
    [ "TransactionFactory", "class_transaction_factory.html", null ]
];