#ifndef __GRADIDO_BLOCKCHAIN_TEST_LIB_DECAY_TEST_H
#define __GRADIDO_BLOCKCHAIN_TEST_LIB_DECAY_TEST_H

#ifndef __GRADIDO_LOGIN_SERVER_TEST_JSON_INTERFACE_TEST_JSON_PACK_TRANSACTION_H
#define __GRADIDO_LOGIN_SERVER_TEST_JSON_INTERFACE_TEST_JSON_PACK_TRANSACTION_H

#include "gtest/gtest.h"

class DecayTest : public ::testing::Test
{

protected:
	void SetUp() override;
	void TearDown() override;
};

#endif //__GRADIDO_LOGIN_SERVER_TEST_JSON_INTERFACE_TEST_JSON_PACK_TRANSACTION_H

#endif //__GRADIDO_BLOCKCHAIN_TEST_LIB_DECAY_TEST_H