#ifndef GRADIDO_BLOCKCHAIN_INTERACTION_VALIDATE_COMMON_ROLE_H
#define GRADIDO_BLOCKCHAIN_INTERACTION_VALIDATE_COMMON_ROLE_H

namespace gradido::interaction::validate {
  
}

#endif //GRADIDO_BLOCKCHAIN_INTERACTION_VALIDATE_COMMON_ROLE_H