#ifndef GRADIDO_BLOCKCHAIN_INTERACTION_VALIDATE_RESULT_TYPE_H
#define GRADIDO_BLOCKCHAIN_INTERACTION_VALIDATE_RESULT_TYPE_H

namespace gradido::interaction::validate {
  enum class ResultType {
    SUCCESS = 0,
    ERROR = 1,
    ERROR_INVALID_INPUT = 2
  };
}
#endif // GRADIDO_BLOCKCHAIN_INTERACTION_VALIDATE_RESULT_TYPE_H