#ifndef __GRADIDO_BLOCKCHAIN_CRYPTO_MNEMONIC_TYPE_H
#define __GRADIDO_BLOCKCHAIN_CRYPTO_MNEMONIC_TYPE_H

enum class MnemonicType {
	GRADIDO_BOOK_GERMAN_RANDOM_ORDER,
	GRADIDO_BOOK_GERMAN_RANDOM_ORDER_FIXED_CASES,
	BIP0039_SORTED_ORDER,
	MAX
};

#endif //__GRADIDO_BLOCKCHAIN_CRYPTO_MNEMONIC_TYPE_H