#ifndef __GRADIDO_BLOCKCHAIN_TEST_INTERACTION_SERIALIZED_TRANSACTIONS_H
#define __GRADIDO_BLOCKCHAIN_TEST_INTERACTION_SERIALIZED_TRANSACTIONS_H

// contain only createAt and version string
constexpr auto emptyTransactionBodyBase64 = "CgASCAiAzLn/BRAAGgMzLjMgAA==";
// contain only createAt, version string and memo
constexpr auto emptyTransactionBodyMemoBase64 =  "CgRtZW1vEggIgMy5/wUQABoDMy4zIAA=";

constexpr auto hieroTransactionIdBase64 = "CgkIqemnUhD+4wESCAgAEAAY/LIH";

constexpr auto communityRootTransactionBase64 =
"CmYKZAoggWcDKZRpiO30UfTEJGkdg89akEOQQogtW7ciQ+9VHvQSQATg0PbEu9LYfch5/F9yvkjb9oLIiHV/1dPW2gr0Am/sri0reEoUZdwykhnWyQmjxHPY+s6pY31enN1+h/Ml/AwSeRIICIDMuf8FEAAaAzMuNSAAWmYKIIFnAymUaYjt9FH0xCRpHYPPWpBDkEKILVu3IkPvVR70EiDX46igkKpEhzJG9cas/Bf/dO4XT1bnvSpV/7gQQfbbHRoglG9YNjDYnHfMH8YdRnJqOt6suRzKsWbAikTKCgoCVcQaAggA";
constexpr auto registeAddressTransactionBase64 =
"CrICCmQKIIFnAymUaYjt9FH0xCRpHYPPWpBDkEKILVu3IkPvVR70EkAE4ND2xLvS2H3Iefxfcr5I2/aCyIh1f9XT1toK9AJv7BgIdGHYWEmzm6sVrAJ5DIcBMMtkZRbvY9Lo4uYswZIICmQKIPTdOYn3VUt6sy490Lf54Rr86QoYEenR9ncWnrRL9EJyEkC0yNmUx8CKaxNoXTN2f8hDBhprz6DTxBUzVWdhDA3uqnjyPqO9wtA2mHFBMpwZKrrUgSucFBoLkhtVrLCPGWkICmQKINsO1hJaFPAwq+0b/IMeCiGM+fq/zufs1YHAwOeI8BfHEkAr+xDWlDs7dCKtpqmrzyvJDbUFEqVXoiBppq3UIqMDyaKt8acPpIJdNKFANBKf230nysXbKBEXzZGUDS4Adp8OEn0SCAiAzLn/BRAAGgMzLjUgAEpqCiD03TmJ91VLerMuPdC3+eEa/OkKGBHp0fZ3Fp60S/RCchABGiBjzRWOpWWqS/0WH7h+8smQbz1wD5vgczJl/odzL/U3ECIg2w7WEloU8DCr7Rv8gx4KIYz5+r/O5+zVgcDA54jwF8coARoCCAA=";
constexpr auto creationTransactionBase64 =
"CmYKZAogtUaRwgwuM9USb0MeLkehFuND29xoywAX28sm2sTUNv8SQAcBv4nbbrbNR06pFhpt3SCWMSQmX+jpMgdoS0zOFV2YXmA7Pp44XlW+kifSV4G93L6YXZCD79MBTeKjsKNOYAISZQodCAISGURlaW5lIGVyc3RlIFNjaG9lcGZ1bmcgOykSCAiAzLn/BRAAGgMzLjUgADozCikKINsO1hJaFPAwq+0b/IMeCiGM+fq/zufs1YHAwOeI8BfHEICt4gQaABoGCLjKuf8FGgIIAA==";
constexpr auto transferTransactionBase64 =
"CmYKZAog2w7WEloU8DCr7Rv8gx4KIYz5+r/O5+zVgcDA54jwF8cSQCv7ENaUOzt0Iq2mqavPK8kNtQUSpVeiIGmmrdQiowPJmwiKZn1dwMZgVpTMv7fyqqoFcANjjAmQeg6ddl0ecQESdwoVCAISEUljaCB0ZWlsZSBtaXQgZGlyEggIgMy5/wUQABoDMy41IAAyTQopCiDbDtYSWhTwMKvtG/yDHgohjPn6v87n7NWBwMDniPAXxxC8wbECGgASICRNKNfMW+j+j7DY4dG5DedgM4YILXk86IdPY1fm5TKtGgIIAA==";
constexpr auto deferredTransferTransactionBase64 =
"CmYKZAog2w7WEloU8DCr7Rv8gx4KIYz5+r/O5+zVgcDA54jwF8cSQCv7ENaUOzt0Iq2mqavPK8kNtQUSpVeiIGmmrdQiowPJXSDIUYfohXSvsgYJ5WfeuRuC4penmAhIjm5PVun/xgASgQEKFggCEhJMaW5rIHp1bSBlaW5sb2VzZW4SCAiAzLn/BRAAGgMzLjUgAFJWCk0KKQog2w7WEloU8DCr7Rv8gx4KIYz5+r/O5+zVgcDA54jwF8cQrIrTAhoAEiAkTSjXzFvo/o+w2OHRuQ3nYDOGCC15POiHT2NX5uUyrRIFCNbC4QMaAggA";
constexpr auto communityFriendsUpdateBase64 = "CmYKZAoggWcDKZRpiO30UfTEJGkdg89akEOQQogtW7ciQ+9VHvQSQATg0PbEu9LYfch5/F9yvkjb9oLIiHV/1dPW2gr0Am/svqIigjI5eYfXfuuwuAbvVvBnhdaPFl0XIHwfe6N98wkSFRIICIDMuf8FEAAaAzMuNSAAQgIIARoCCAA=";

constexpr auto invalidBodyTestPayload = "''To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.''\n - Ralph Waldo Emerson ";
// contain invalidBodyTestPayload as body bytes
// signed with g_KeyPairs[3]
constexpr auto gradidoTransactionSignedInvalidBody = 
"CmYKZAog9N05ifdVS3qzLj3Qt/nhGvzpChgR6dH2dxaetEv0QnISQLTI2ZTHwIprE2hdM3Z/yEMGGmvPoNPEFTNVZ2EMDe6qRe/ObgOMp8HSG8+6mLD2+p7Wx1+c2mzhhttAASDAmgISigEnJ1RvIGJlIHlvdXJzZWxmIGluIGEgd29ybGQgdGhhdCBpcyBjb25zdGFudGx5IHRyeWluZyB0byBtYWtlIHlvdSBzb21ldGhpbmcgZWxzZSBpcyB0aGUgZ3JlYXRlc3QgYWNjb21wbGlzaG1lbnQuJycKIC0gUmFscGggV2FsZG8gRW1lcnNvbiAaAggA";
// contain a transfer transaction
constexpr auto completeConfirmedTransaction = 
"CAcS6AEKZgpkCiCBZwMplGmI7fRR9MQkaR2Dz1qQQ5BCiC1btyJD71Ue9BJABODQ9sS70th9yHn8X3K+SNv2gsiIdX/V09baCvQCb+yEj2Dd/fzShIYqf3pooIMwJ01BkDJdNGBZs5MDzEAkChJ6ChkIAhIVRGFua2UgZnVlciBkZWluIFNlaW4hEggIgMy5/wUQABoDMy41IAAyTAooCiDbDtYSWhTwMKvtG/yDHgohjPn6v87n7NWBwMDniPAXxxCUmD0aABIgJE0o18xb6P6PsNjh0bkN52AzhggteTzoh09jV+blMq0aAggAGggIwvK5/wUQACIDMy43KiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADIZCAIaFQoJCKnpp1IQ/uMBEggIABAAGPyyBzomCiDbDtYSWhTwMKvtG/yDHgohjPn6v87n7NWBwMDniPAXxxDAhD06JwogJE0o18xb6P6PsNjh0bkN52AzhggteTzoh09jV+blMq0Q65SlBEAC";
#endif //__GRADIDO_BLOCKCHAIN_TEST_INTERACTION_SERIALIZED_TRANSACTIONS_H
