#ifndef __GRADIDO_BLOCKCHAIN_TEST_INTERACTION_SERIALIZED_TRANSACTIONS_H
#define __GRADIDO_BLOCKCHAIN_TEST_INTERACTION_SERIALIZED_TRANSACTIONS_H

// contain only createAt and version string
constexpr auto emptyTransactionBodyBase64 = "CgASCAiAzLn/BRAAGgMzLjMgAA==";
// contain only createAt, version string and memo
constexpr auto emptyTransactionBodyMemoBase64 =  "CgRtZW1vEggIgMy5/wUQABoDMy4zIAA=";

constexpr auto hieroTransactionIdBase64 = "CgkIqemnUhD+4wESCAgAEAAY/LIH";

constexpr auto communityRootTransactionBase64 =
"CmYKZAogqtErqCa5EURXVUxMVX+jqHivnyH4FiGww+YWFQYRKCkSQEmnjV7+r6Y7z0CrSceGF7xwvXFX4Hej50MV2W4ekQSJ53kekrjE5JWzGrG9K8RCnJrSoIXlXFYUcR38gn98/QoSdRIGCIDMuf8FGgMzLjVaZgogqtErqCa5EURXVUxMVX+jqHivnyH4FiGww+YWFQYRKCkSIBS4pthWO7s1l999gnW3C1agRhpbeR1jwIzAWUfSBhyJGiBGb91zu4FifzYPyOaLPep/wCCUs6bxzSrfvTmk8y4lnhoA";
constexpr auto registeAddressTransactionBase64 =
"CrICCmQKIKrRK6gmuRFEV1VMTFV/o6h4r58h+BYhsMPmFhUGESgpEkDdBYnw6FWxdQXZ+K9cnXB3JDJFQT8KVhC1yqgnTKNuLgjiyxK6K9vzZEeFHiE6wXoxQ7o4wVPLnEd8QVItATQHCmQKILxxJbfkt7U00jLCFcLLzjRAiGBKDoruOTLpv0FqBs/+EkDc28tzP3cvgcwM4xCEktvEhPw0ikUb2xTSUa3zG5N5dKxMJ5GPJS/n78pLejfjQ8OiVm8NP7LP9YXZAyHlT8MFCmQKIO/ykZNQpTrID4mAYrfGf/gCgkX0zETgjvIviFFxVU87EkC4J/ByDZPNlb6Jgi39rH+B3YgbgITV2kL0S6HmspFymCouglWwR24ym7+c6J0CSfOyFTiSNAqLhzsGxCmc6doOEnkSBgiAzLn/BRoDMy41SmoKILxxJbfkt7U00jLCFcLLzjRAiGBKDoruOTLpv0FqBs/+EAEaIB/kH3lmpLYaljiGoPpNE22FeUJNnAKidR77oOjlVZ9hIiDv8pGTUKU6yA+JgGK3xn/4AoJF9MxE4I7yL4hRcVVPOygBGgA=";
constexpr auto creationTransactionBase64 =
"CmYKZAogyy3XdFIKQdmOo6znQO6zP6F5nXcyrbd24930wGPWAbwSQLoWkuWdqFViwdGaETYuCAGtASEcfNc9dMocRAylm7S73bqNYsNuuqCp9fQeWNG4ZpIgO5ksd4b9Xq1gkKXV8wESXwodCAISGURlaW5lIGVyc3RlIFNjaG9lcGZ1bmcgOykSBgiAzLn/BRoDMy41OjEKJwog7/KRk1ClOsgPiYBit8Z/+AKCRfTMROCO8i+IUXFVTzsQgK3iBBoGCLjKuf8FGgA=";
constexpr auto transferTransactionBase64 =
"CmYKZAog7/KRk1ClOsgPiYBit8Z/+AKCRfTMROCO8i+IUXFVTzsSQE77i3/OM2356rKFJYaktfYQpVTj3a0U/D+G5rYQ9L8mcU+OtSYG0sx/LLtBDB9gn/9Pu6NlHkVLib4fj5BXywAScQoVCAISEUljaCB0ZWlsZSBtaXQgZGlyEgYIgMy5/wUaAzMuNTJLCicKIO/ykZNQpTrID4mAYrfGf/gCgkX0zETgjvIviFFxVU87ELzBsQISIH71fuNOTK5eAUA0t/gEO6ZA0aJvB9YirDQuZK11ufYNGgA=";
constexpr auto deferredTransferTransactionBase64 =
"CmYKZAog7/KRk1ClOsgPiYBit8Z/+AKCRfTMROCO8i+IUXFVTzsSQLNxKNCE73Y/6R6DCWPghfgrHGyI3j7SaDTDbRq2EJbrcDpMQbU7zNUffvatlheOJltUXy8++KFI0GFy/0JMZAsSewoWCAISEkxpbmsgenVtIGVpbmxvZXNlbhIGCIDMuf8FGgMzLjVSVApLCicKIO/ykZNQpTrID4mAYrfGf/gCgkX0zETgjvIviFFxVU87EKyK0wISIH71fuNOTK5eAUA0t/gEO6ZA0aJvB9YirDQuZK11ufYNEgUI1sLhAxoA";
constexpr auto communityFriendsUpdateBase64 = "CmYKZAogqtErqCa5EURXVUxMVX+jqHivnyH4FiGww+YWFQYRKCkSQP7aJIvxwxyoUFMAOXQsI5tBWJtr5RxDMiUKJKNUOxJsY3aR8z16kzuYamk9/kPuMVS8NHCEzVcbEFCqQTAqYQoSERIGCIDMuf8FGgMzLjVCAggBGgA=";

constexpr auto invalidBodyTestPayload = "''To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.''\n - Ralph Waldo Emerson ";
// contain invalidBodyTestPayload as body bytes
// signed with g_KeyPairs[3]
constexpr auto gradidoTransactionSignedInvalidBody = 
"CmYKZAogvHElt+S3tTTSMsIVwsvONECIYEoOiu45Mum/QWoGz/4SQHE06IAAgOfDPhtZAEBF6HnIx1yfNyYR3HK105o5OzARd1ThFyl8gJJk4UddegCOu8c+y2bWnNEEi/WC0KTfhQsSigEnJ1RvIGJlIHlvdXJzZWxmIGluIGEgd29ybGQgdGhhdCBpcyBjb25zdGFudGx5IHRyeWluZyB0byBtYWtlIHlvdSBzb21ldGhpbmcgZWxzZSBpcyB0aGUgZ3JlYXRlc3QgYWNjb21wbGlzaG1lbnQuJycKIC0gUmFscGggV2FsZG8gRW1lcnNvbiAaAA==";
// contain a transfer transaction
constexpr auto completeConfirmedTransaction = 
"CAcS4AEKZgpkCiCq0SuoJrkRRFdVTExVf6OoeK+fIfgWIbDD5hYVBhEoKRJAv2AIG7yODq5Oy5wJ6iNfZ3zzAnEumRXIA/qZw93+B6Fte100RFFTypTs4FO5Unu+FNIW+fouApjYMPXu8blVCBJ0ChkIAhIVRGFua2UgZnVlciBkZWluIFNlaW4hEgYIgMy5/wUaAzMuNTJKCiYKIO/ykZNQpTrID4mAYrfGf/gCgkX0zETgjvIviFFxVU87EJSYPRIgfvV+405Mrl4BQDS3+AQ7pkDRom8H1iKsNC5krXW59g0aABoGCMLyuf8FIgMzLjcqIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMhUIAhoRCgkIqemnUhD+4wESBBj8sgc6Jgog7/KRk1ClOsgPiYBit8Z/+AKCRfTMROCO8i+IUXFVTzsQwIQ9OicKIH71fuNOTK5eAUA0t/gEO6ZA0aJvB9YirDQuZK11ufYNEOuUpQRAAg==";
#endif //__GRADIDO_BLOCKCHAIN_TEST_INTERACTION_SERIALIZED_TRANSACTIONS_H
