#ifndef __GRADIDO_BLOCKCHAIN_TEST_INTERACTION_SERIALIZED_TRANSACTIONS_H
#define __GRADIDO_BLOCKCHAIN_TEST_INTERACTION_SERIALIZED_TRANSACTIONS_H

// contain only createAt and version string
constexpr auto emptyTransactionBodyBase64 = "CgASCAiAzLn/BRAAGgMzLjMgAA==";
// contain only createAt, version string and memo
constexpr auto emptyTransactionBodyMemoBase64 =  "CgRtZW1vEggIgMy5/wUQABoDMy4zIAA=";

constexpr auto hieroTransactionIdBase64 = "CgkIqemnUhD+4wESCAgAEAAY/LIH";

constexpr auto communityRootTransactionBase64 =
"CmYKZAoggWcDKZRpiO30UfTEJGkdg89akEOQQogtW7ciQ+9VHvQSQATg0PbEu9LYfch5/F9yvkjb9oLIiHV/1dPW2gr0Am/sbxLVA8xr9mWVI3lIluf906FvLHLHWjMeN+/7ggVGnw8SdRIGCIDMuf8FGgMzLjVaZgoggWcDKZRpiO30UfTEJGkdg89akEOQQogtW7ciQ+9VHvQSINfjqKCQqkSHMkb1xqz8F/907hdPVue9KlX/uBBB9tsdGiCUb1g2MNicd8wfxh1Gcmo63qy5HMqxZsCKRMoKCgJVxBoCCAA=";
constexpr auto registeAddressTransactionBase64 =
"CswBCmQKIIFnAymUaYjt9FH0xCRpHYPPWpBDkEKILVu3IkPvVR70EkAE4ND2xLvS2H3Iefxfcr5I2/aCyIh1f9XT1toK9AJv7I6TzVozwJhawERgisw2KZ4Q/pwfnkm0eMBgyuVVTOEOCmQKINsO1hJaFPAwq+0b/IMeCiGM+fq/zufs1YHAwOeI8BfHEkAr+xDWlDs7dCKtpqmrzyvJDbUFEqVXoiBppq3UIqMDyY3zHtVazcoS18pRPE5c8+RrUHZXk2W8Dgx5qK0tWMAOEnkSBgiAzLn/BRoDMy41SmoKIPTdOYn3VUt6sy490Lf54Rr86QoYEenR9ncWnrRL9EJyEAEaIGPNFY6lZapL/RYfuH7yyZBvPXAPm+BzMmX+h3Mv9TcQIiDbDtYSWhTwMKvtG/yDHgohjPn6v87n7NWBwMDniPAXxygBGgIIAA==";
constexpr auto creationTransactionBase64 =
"CmYKZAogtUaRwgwuM9USb0MeLkehFuND29xoywAX28sm2sTUNv8SQAcBv4nbbrbNR06pFhpt3SCWMSQmX+jpMgdoS0zOFV2Y07LCg3FCuy01HfecF6OrfQ1dDgALQDr41Orn66cUlQUSXQodCAISGURlaW5lIGVyc3RlIFNjaG9lcGZ1bmcgOykSBgiAzLn/BRoDMy41Oi8KJQog2w7WEloU8DCr7Rv8gx4KIYz5+r/O5+zVgcDA54jwF8cQ6AcaBgi4yrn/BRoCCAA=";
constexpr auto transferTransactionBase64 =
"CmYKZAog2w7WEloU8DCr7Rv8gx4KIYz5+r/O5+zVgcDA54jwF8cSQCv7ENaUOzt0Iq2mqavPK8kNtQUSpVeiIGmmrdQiowPJ4+w14s8IBOd0OYj6Ko7m6D2qhNzq/y1SU8Mr3HXSZwASbwoVCAISEUljaCB0ZWlsZSBtaXQgZGlyEgYIgMy5/wUaAzMuNTJJCiUKINsO1hJaFPAwq+0b/IMeCiGM+fq/zufs1YHAwOeI8BfHEPQDEiAkTSjXzFvo/o+w2OHRuQ3nYDOGCC15POiHT2NX5uUyrRoCCAA=";
constexpr auto deferredTransferTransactionBase64 =
"CmYKZAog2w7WEloU8DCr7Rv8gx4KIYz5+r/O5+zVgcDA54jwF8cSQCv7ENaUOzt0Iq2mqavPK8kNtQUSpVeiIGmmrdQiowPJWqTN6Q2qwaH1AeUuSd87HPeCLGXnuMgqGpYF1x0iCgUSeQoWCAISEkxpbmsgenVtIGVpbmxvZXNlbhIGCIDMuf8FGgMzLjVSUgpJCiUKINsO1hJaFPAwq+0b/IMeCiGM+fq/zufs1YHAwOeI8BfHEKsEEiAkTSjXzFvo/o+w2OHRuQ3nYDOGCC15POiHT2NX5uUyrRIFCNbC4QMaAggA";
constexpr auto communityFriendsUpdateBase64 = "CmYKZAoggWcDKZRpiO30UfTEJGkdg89akEOQQogtW7ciQ+9VHvQSQATg0PbEu9LYfch5/F9yvkjb9oLIiHV/1dPW2gr0Am/svqIigjI5eYfXfuuwuAbvVvBnhdaPFl0XIHwfe6N98wkSFRIICIDMuf8FEAAaAzMuNSAAQgIIARoCCAA=";

constexpr auto invalidBodyTestPayload = "''To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.''\n - Ralph Waldo Emerson ";
// contain invalidBodyTestPayload as body bytes
// signed with g_KeyPairs[3]
constexpr auto gradidoTransactionSignedInvalidBody = 
"CmYKZAog9N05ifdVS3qzLj3Qt/nhGvzpChgR6dH2dxaetEv0QnISQLTI2ZTHwIprE2hdM3Z/yEMGGmvPoNPEFTNVZ2EMDe6qRe/ObgOMp8HSG8+6mLD2+p7Wx1+c2mzhhttAASDAmgISigEnJ1RvIGJlIHlvdXJzZWxmIGluIGEgd29ybGQgdGhhdCBpcyBjb25zdGFudGx5IHRyeWluZyB0byBtYWtlIHlvdSBzb21ldGhpbmcgZWxzZSBpcyB0aGUgZ3JlYXRlc3QgYWNjb21wbGlzaG1lbnQuJycKIC0gUmFscGggV2FsZG8gRW1lcnNvbiAaAggA";
// contain a transfer transaction
constexpr auto completeConfirmedTransaction = 
"CAcS4AEKZgpkCiCBZwMplGmI7fRR9MQkaR2Dz1qQQ5BCiC1btyJD71Ue9BJABODQ9sS70th9yHn8X3K+SNv2gsiIdX/V09baCvQCb+x1hgm+B67XNgAFs0Vuv7hLq3q2ZVgzugWu+yOdTw2GBBJyChkIAhIVRGFua2UgZnVlciBkZWluIFNlaW4hEgYIgMy5/wUaAzMuNTJICiQKINsO1hJaFPAwq+0b/IMeCiGM+fq/zufs1YHAwOeI8BfHEGQSICRNKNfMW+j+j7DY4dG5DedgM4YILXk86IdPY1fm5TKtGgIIABoICMLyuf8FEAAiAzMuNyogAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAyGQgCGhUKCQip6adSEP7jARIICAAQABj8sgc6Jgog2w7WEloU8DCr7Rv8gx4KIYz5+r/O5+zVgcDA54jwF8cQwIQ9OicKICRNKNfMW+j+j7DY4dG5DedgM4YILXk86IdPY1fm5TKtEOuUpQRAAg==";
#endif //__GRADIDO_BLOCKCHAIN_TEST_INTERACTION_SERIALIZED_TRANSACTIONS_H
